const apiData = {
    payload: {
      restaurantDetails: {
        id: "",
        name: "",
        addressDetails: {
          houseNo: "",
          area: "",
          landmark: "",
          city: "",
          state: "",
          pinCode: "",
          country: "",
        },
        phone: [
          {
            phoneNumber: "",
            stdIsdCode: "",
            phoneType: "",
          },
        ],
        email: "",
        socialMediaDetails: [
          {
            channelName: "",
            url: "",
          },
        ],
        imageUrl: "",
        foodMenu: [
          {
            categoryId: "1",
            category: "Today's Special",
            position: 0,
            dishes: [
              {
                id: "1",
                name: "Sev tameta Sabji",
                description: "",
                qtyUnit: "",
                price: "150",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Dhokla",
                description: "",
                qtyUnit: "",
                price: "100",
                imageUrl: "",
                position: 1,
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
          {
            categoryId: "2",
            category: "Recomended",
            position: 1,
            dishes: [
              {
                id: "1",
                name: "Burger",
                description: "",
                qtyUnit: "",
                price: "250",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Khaman",
                description: "",
                qtyUnit: "",
                price: "140",
                position: 1,
                imageUrl: "",
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
          {
            categoryId: "3",
            category: "Gujarati",
            position: 2,
            dishes: [
              {
                id: "1",
                name: "Roti",
                description: "",
                qtyUnit: "",
                price: "30",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Khaman",
                description: "",
                qtyUnit: "",
                price: "140",
                position: 1,
                imageUrl: "",
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
          {
            categoryId: "4",
            category: "Tea & Beverages",
            position: 3,
            dishes: [
              {
                id: "1",
                name: "Special Tea",
                description: "",
                qtyUnit: "",
                price: "35",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Coffee",
                description: "",
                qtyUnit: "",
                price: "50",
                position: 1,
                imageUrl: "",
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
          {
            categoryId: "5",
            category: "Rollas & Sandwitches",
            position: 4,
            dishes: [
              {
                id: "1",
                name: "Rolls",
                description: "",
                qtyUnit: "",
                price: "58",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Sandwitch",
                description: "",
                qtyUnit: "",
                price: "150",
                position: 1,
                imageUrl: "",
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
          {
            categoryId: "5",
            category: "Ice cream & Shakes",
            position: 5,
            dishes: [
              {
                id: "1",
                name: "Ice cream",
                description: "",
                qtyUnit: "",
                price: "158",
                imageUrl: "",
                position: 0,
                tags: ["spicy", "indian", "north-indian"],
              },
              {
                id: "2",
                name: "Chikku Shake",
                description: "",
                qtyUnit: "",
                price: "250",
                position: 1,
                imageUrl: "",
                tags: ["spicy", "indian", "north-indian"],
              },
            ],
          },
        ],
      },
    },
  }
  
export default apiData;
